package nl.tudelft.oopp.demo.controllers;

import java.util.HashSet;
import java.util.Set;

import nl.tudelft.oopp.demo.entities.Building;
import nl.tudelft.oopp.demo.entities.Room;
import nl.tudelft.oopp.demo.repositories.BuildingRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;


@Repository
@RestController // This means that this class is a Controller
@RequestMapping(path = "/building") // This means URL's start with /building (after Application path)
public class BuildingController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private BuildingRepository buildingRepository;

    /**
     * Adds a building.
     * @param name = the name of the building
     * @return String to see if your request passed
     */
    @PostMapping(path = "/add") // Map ONLY POST Requests
    @ResponseBody
    public String addNewBuilding(
            @RequestParam String name,
            @RequestParam String street,
            @RequestParam int houseNumber
    ) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        Building building = new Building();
        building.setName(name);
        building.setStreet(street);
        building.setHouseNumber(houseNumber);
        building.setRooms(new HashSet<>());
        buildingRepository.save(building);
        return "Saved";
    }

    /**
     * Deletes a building.
     * @param id = the id of the building
     * @return String to see if your request passed
     */
    @PostMapping(path = "/delete")
    @ResponseBody
    public String deleteBuilding(@RequestParam int id) {
        if (!buildingRepository.existsById(id)) {
            return "Building with ID: " + id + " Does not exist!";
        }
        if (buildingRepository.findById(id).get().hasRooms()) {
            return "This building cannot be deleted as it has at least one room. Delete the room before deleting the building!";
        }
        buildingRepository.deleteById(id);
        return "Deleted!";
    }

    /**
     * Updates a database attribute.
     * @param id = the building id
     * @param attribute = the attribute that is changed
     * @param value = the new value of the attribute
     * @return message if it passes
     */
    @PostMapping(path = "/update")
    @ResponseBody
    public String updateBuildingName(@RequestParam int id, @RequestParam String attribute, @RequestParam String value) {
        if (!buildingRepository.existsById(id)) {
            return "Building with ID: " + id + " Does not exist!";
        }
        Building building = buildingRepository.getOne(id);
        switch (attribute) {
            case "name":
                building.setName(value);
                break;
            case "street":
                building.setStreet(value);
                break;
            case "houseNumber":
                building.setHouseNumber(Integer.parseInt(value));
                break;
            default:
                return "No attribute with name " + attribute + " found!";
        }
        buildingRepository.save(building);
        return "The attribute has been set!";
    }

    /**
     * Lists all buildings.
     * @return all buildings
     */
    @GetMapping(path = "/all")
    @ResponseBody
    public Iterable<Building> getAllBuildings() {
        // This returns a JSON or XML with the users
        return buildingRepository.findAll();
    }

    /**
     * Finds a building with the specified id.
     * @param id = the id of the building
     * @return a building that matches the id
     */
    @GetMapping(path = "/find/{buildingId}")
    @ResponseBody
    public Building findBuilding(@PathVariable(value = "buildingId") int id) {
        return buildingRepository.findById(id).orElse(null);
    }

    /**
     * Return all rooms that are in the building with the specified id.
     * @param id = the id of the building
     * @return all rooms that are in the building that matches the id
     */
    @GetMapping(path = "/rooms/{buildingId}")
    @ResponseBody
    public Set<Room> getRooms(@PathVariable(value = "buildingId") int id) {
        if (buildingRepository.findById(id).isEmpty()) {
            return null;
        }
        return buildingRepository.findById(id).get().getRooms();
    }

}
