package nl.tudelft.oopp.demo.controllers;

import java.util.HashSet;
import java.util.Set;

import nl.tudelft.oopp.demo.entities.Building;
import nl.tudelft.oopp.demo.entities.Room;
import nl.tudelft.oopp.demo.repositories.BuildingRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;



@Repository
@RestController // This means that this class is a Controller
@RequestMapping(path = "/building") // This means URL's start with /building (after Application path)
public class BuildingController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private BuildingRepository buildingRepository;

    /**
     * Adds a building to the database.
     * @param name = the name of the new building.
     * @return String containing the result of your request.
     */
    @PostMapping(path = "/add") // Map ONLY POST Requests
    @ResponseBody
    public String addNewBuilding(
            @RequestParam String name,
            @RequestParam String street,
            @RequestParam int houseNumber
    ) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        Building building = new Building();
        building.setName(name);
        building.setStreet(street);
        building.setHouseNumber(houseNumber);
        building.setRooms(new HashSet<>());
        buildingRepository.save(building);
        return "Saved";
    }

    /**
     * Deletes a building from the database.
     * @param id = the id of the existing building to be deleted.
     * @return String containing the result of your request.
     */
    @DeleteMapping(path = "/delete/{buildingID}")
    @ResponseBody
    public String deleteBuilding(@PathVariable(value = "buildingID") int id) {
        if (!buildingRepository.existsById(id)) {
            return "Building with ID: " + id + " Does not exist!";
        }
        if (buildingRepository.findById(id).get().hasRooms()) {
            return "This building cannot be deleted as it has at least one room. Delete the room before deleting the building!";
        }
        buildingRepository.deleteById(id);
        return "Deleted!";
    }

    /**
     * Updates an attribute of a building in the database.
     * @param id = the id of the building whose value is to be updated.
     * @param attribute = the attribute whose value is updated.
     * @param value = the new value.
     * @return String containing the result of your request.
     */
    @PostMapping(path = "/update")
    @ResponseBody
    public String updateBuilding(@RequestParam int id, @RequestParam String attribute, @RequestParam String value) {
        if (!buildingRepository.existsById(id)) {
            return "Building with ID: " + id + " Does not exist!";
        }
        Building building = buildingRepository.getOne(id);
        switch (attribute.toLowerCase()) {
            case "name":
                building.setName(value);
                break;
            case "street":
                building.setStreet(value);
                break;
            case "housenumber":
                building.setHouseNumber(Integer.parseInt(value));
                break;
            default:
                System.out.println(attribute);
                return "No attribute with name " + attribute + " found!";
        }
        buildingRepository.save(building);
        return "The attribute has been set!";
    }

    /**
     * Lists all buildings in the database.
     * @return Iterable of all buildings in the database.
     */
    @GetMapping(path = "/all")
    @ResponseBody
    public Iterable<Building> getAllBuildings() {
        // This returns a JSON or XML with the users
        return buildingRepository.findAll();
    }

    /**
     * Retrieves the building with the specified id.
     * @param id = the id of the building.
     * @return Building that matches the id.
     */
    @GetMapping(path = "/find/{buildingID}")
    @ResponseBody
    public Building findBuilding(@PathVariable(value = "buildingID") int id) {
        return buildingRepository.findById(id).orElse(null);
    }

    /**
     * Return all rooms that are in the building with the specified id.
     * @param id = the id of the building.
     * @return Set of all rooms in the retrieved building.
     */
    @GetMapping(path = "/rooms/{buildingId}")
    @ResponseBody
    public Set<Room> getRooms(@PathVariable(value = "buildingId") int id) {
        if (buildingRepository.findById(id).isEmpty()) {
            return null;
        }
        return buildingRepository.findById(id).get().getRooms();
    }

}
