package nl.tudelft.oopp.demo.controllers;

import nl.tudelft.oopp.demo.entities.User;
import nl.tudelft.oopp.demo.repositories.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

@Repository
@RestController // This means that this class is a Controller
@RequestMapping(path = "/user") // This means URL's start with /user (after Application path)
public class UserController {
    @Autowired // This means to get the bean called UserRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    /**
     * Adds a user.
     * @param name = the name of the user
     * @return String to see if your request passed
     */
    @PostMapping(path = "/add") // Map ONLY POST Requests
    @ResponseBody
    public String addUser(
            @RequestParam String email,
            @RequestParam String password,
            @RequestParam String name,
            @RequestParam String surname,
            @RequestParam String faculty
    ) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request.
        if (userRepository.existsById(email)) {
            return "The account with email " + email + " already exists!";
        }
        User user = new User();

        user.setEmail(email);
        user.setPassword(password);
        user.setName(name);
        user.setSurname(surname);
        user.setFaculty(faculty);
        userRepository.save(user);
        return "Account created!";
    }

    /**
     * Deletes an account.
     * @param email = the email of the account
     * @return String to see if your request passed
     */
    @PostMapping(path = "/delete")
    @ResponseBody
    public String deleteAccount(@RequestParam String email) {
        if (!userRepository.existsById(email)) {
            return "The account with email " + email + " does not exist!";
        }
        userRepository.deleteById(email);
        return "The account with email " + email + " has been deleted!";
    }

    /**
     * Updates a database attribute "password".
     * @param email = the account email
     * @param password = The account password
     * @return message if it passes
     */
    @PostMapping(path = "/update_password")
    @ResponseBody
    public String updatePassword(@RequestParam String email, @RequestParam String password) {
        if (!userRepository.existsById(email)) {
            return "The account with email " + email + " does not exist!";
        }
        User user = userRepository.getOne(email);
        String old = user.getPassword();
        user.setPassword(password);
        userRepository.save(user);
        return "The previous password " + old + " has been changed to " + password + " for the account with email " + email + "!";
    }

    /**
     * Updates a database attribute "name".
     * @param email = the account email
     * @param name = The account name
     * @return message if it passes
     */
    @PostMapping(path = "/update_name")
    @ResponseBody
    public String updateName(@RequestParam String email, @RequestParam String name) {
        if (!userRepository.existsById(email)) {
            return "The account with email " + email + " does not exist!";
        }
        User user = userRepository.getOne(email);
        String old = user.getName();
        user.setName(name);
        userRepository.save(user);
        return "The previous name " + old + " has been changed to " + name + " for the account with email " + email + "!";
    }

    /**
     * Updates a database attribute "surname".
     * @param email = the account email
     * @param surname = The account surname
     * @return message if it passes
     */
    @PostMapping(path = "/update_surname")
    @ResponseBody
    public String updateSurname(@RequestParam String email, @RequestParam String surname) {
        if (!userRepository.existsById(email)) {
            return "The account with email " + email + " does not exist!";
        }
        User user = userRepository.getOne(email);
        String old = user.getSurname();
        user.setSurname(surname);
        userRepository.save(user);
        return "The previous surname " + old + " has been changed to " + surname + " for the account with email " + email + "!";
    }

    /**
     * Updates a database attribute "faculty".
     * @param email = the account email
     * @param faculty = The account surname
     * @return message if it passes
     */
    @PostMapping(path = "/update_faculty")
    @ResponseBody
    public String updateFaculty(@RequestParam String email, @RequestParam String faculty) {
        if (!userRepository.existsById(email)) {
            return "The account with email " + email + " does not exist!";
        }
        User user = userRepository.getOne(email);
        String old = user.getFaculty();
        user.setFaculty(faculty);
        userRepository.save(user);
        return "The previous faculty " + old + " has been changed to " + faculty + " for the account with email " + email + "!";
    }

    /**
     * Lists all accounts.
     * Should be removed for the finished version!
     * @return all accounts
     */
    @GetMapping(path = "/all")
    @ResponseBody
    public Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    /**
     * Finds an account by its email.
     * @return an account that has the specified email or null if no such account exists
     */
    @GetMapping(path = "/find")
    @ResponseBody
    public User getUser(@RequestParam String email) {
        if (!userRepository.existsById(email)) {
            return null;
            //return "The account with email " + email + " does not exist!";
        }
        User user = userRepository.getOne(email);
        return user;
    }

}
